<?php
declare (strict_types=1);

namespace app\api_admin\controller;

use app\api_admin\library\ApiBase;
use app\cigo_admin_core\library\traites\CheckArgs;

/**
 * V1版本公共基类
 *
 * Class CommonV1
 * @package app\api_admin\controller\v1
 */
class CommonV1 extends ApiBase
{
    use CheckArgs;

    protected $args = [];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->checkTimeStamp();
        $this->checkSign();

        $this->args = input();
    }
}
